title: Bigstone Wiki
description: A comprehensive guide to Bigstone, covering its features, usage, and best practices.
theme: minima

header_pages:
  - pages/index.md
  - pages/standards.md
  - pages/components.md
