title: Bigstone Wiki
description: A comprehensive guide to Bigstone, covering its features, usage, and best practices.
theme: minima
favicon: assets/favicon.ico # Adjust path as neede

header_pages:
  - index.md
  - standards.md
  - components.md
