name: Update Wiki Timestamps

on:
  push:
    branches:
      - main
  workflow_dispatch:      # allows manual run

jobs:
  update-timestamps:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get current UTC time
        id: get-time
        run: echo "time=$(date -u +'%Y-%m-%d, %H:%M:%S,%3N UTC')" >> "$GITHUB_OUTPUT"

      - name: Replace last line of each .md file
        run: |
          for file in $(find . -name '*.md'); do
            tmpfile=$(mktemp)
            last_line=$(tail -n 1 "$file")
            if [[ "$last_line" == "_Last updated:"* ]]; then
              head -n -1 "$file" > "$tmpfile" || true  # skip if only 1 line
            else
              cp "$file" "$tmpfile"  # do not remove the last line if it isn't a last updated one
              echo "" >> "$tmpfile"
            fi
            echo "_Last updated: ${{ steps.get-time.outputs.time }}_" >> "$tmpfile"
            mv "$tmpfile" "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update last-updated timestamps in wiki" || echo "No changes"
          git push origin main
